### ISSUE TITLE
Za 10

### ISSUE THREAD

**Issue by andrejbauer** [kerkocmatija/Chit-Chat#1]
- [x] Odstrani vse menuje, ki ne počnejo ničesar.
- [x] V pomoči napiši kar koristnega (na primer, kaj delajo gumbki, ali kaj je treba narediti, da se pošlje zasebno sporočilo), ali pa odstrani pomoč.
- [x] "Za slabovidne" ne deluje na mojem Macu. Pa namesto "Za slabovidne" bi bilo bolje imeti "Večji font". In če imaš "večji font", zakaj ne tudi "manjši font"? Namesto fonta `Calibri`, ki ga nekateri nimamo, uporabi raje enega od v naprej definiranih fontov ([logical font family names](http://www.java2s.com/Tutorials/Java/Java_Swing/1520__Java_Swing_Font.htm)).
- [x] Lahko bi se videl čas pošiljanja.
- [x] Popravi šumnike, da bo vsa source koda v formatu UTF-8, glej  [tole sporočilo](https://ucilnica1718.fmf.uni-lj.si/mod/forum/discuss.php?d=11202) na spletni učilnici.
- [x] Nastavi `weighty = 0` v vrstici 208 v `ChatFrame` (constraint za `inputKomu` je narobe). Potem tudi odstrani copranje z maximum size, s katerim si poskušal popraviti razpored.
- [x] Lepo zamakni kodo. To zna Eclipse sam: izbereš kos kode in izbereš Source->Correct indentations.

**Comment by kerkocmatija** [comment]
Odstranjene nepotrebne komponente, počiščena koda ter urejeno kodiranje z UTF-8.
